# render.yaml  – keep‑alive ping every 10 minutes
jobs:
  - type: cron
    name: stay-alive
    runtime: image              # tell Render to run an OCI image
    image: curlimages/curl:latest
    schedule: "*/10 * * * *"    # every 10 min
    command: ["curl", "-fsS", "https://vpds-rec-backend.onrender.com/health"]
